# Generated by Django 4.2.3 on 2023-10-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='fotos/default.png', null=True, upload_to='fotos'),
        ),
    ]
