# Generated by Django 5.0.2 on 2024-03-02 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_servicio_creador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='creador',
        ),
    ]
