# Generated by Django 5.0.2 on 2024-03-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_remove_servicio_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Padres'), (2, 'Ninos/Abuelos'), (3, 'Nannys'), (4, 'Administrador')], default=1),
        ),
    ]
