# Generated by Django 5.0.2 on 2024-03-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0014_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Padre'), (2, 'Ninos/Abuelos'), (3, 'Nanny'), ('Cuco2024', 'Administrador')], default=1),
        ),
    ]
