# Generated by Django 5.0.2 on 2024-03-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0018_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Padre'), (2, 'Ninos/Abuelos'), (3, 'Nanny'), (4, 'Administrador')], default=1),
        ),
    ]
