# Generated by Django 5.0.2 on 2024-03-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0019_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservacion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(max_length=30)),
                ('tipoServicio', models.CharField(max_length=100)),
            ],
        ),
    ]
