# Generated by Django 5.0.2 on 2024-03-04 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0020_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(choices=[(1, 'Padre'), (3, 'Ninos/Abuelos'), (2, 'Nanny'), (4, 'Administrador')], default=1),
        ),
    ]
