# Generated by Django 5.0.2 on 2024-03-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0022_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='propietario',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
