# Generated by Django 5.0.2 on 2024-03-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0023_servicio_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='propietario',
            field=models.CharField(max_length=200),
        ),
    ]
